jobs:
  reserva:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Instalar Google Chrome 126 (versão fixa)
        run: |
          sudo apt-get remove -y google-chrome-stable || true
          sudo rm -f /etc/apt/sources.list.d/google-chrome.list || true
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_126.0.6478.114-1_amd64.deb
          sudo dpkg -i google-chrome-stable_126.0.6478.114-1_amd64.deb
          google-chrome --version

      - name: Instalar Chromedriver versão 126
        run: |
          CHROME_DRIVER_VERSION=126.0.6478.114
          wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version


      - name: Executar script com tentativas
        run: |
          export DISPLAY=:0
          for i in {1..3}; do
            echo "Tentativa $i/3"
            if python reserva.py; then
              echo "Script executado com sucesso"
              break
            else
              echo "Falhou, tentando novamente..."
              sleep 5
            fi
          done
